In [1]:
import pandas as pd

In [2]:
#Step 1: Read the data
df = pd.read_csv(r"E:/Dataset/winequality-red.csv")
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [4]:
# Step 2: Data Pre-Processing:
# Check the missing values in dataset
df.isnull().sum() #Sum gives you the missing values present in data

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [6]:
# Step 3 : Defining X and Y
Y = df[['quality']]
X = df.drop(columns = ['quality'])

# Step 4 : Split the data
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, train_size = 0.8, random_state=1234)
 
len(X_train), len(X_test), len(Y_train), len(Y_test)

(1279, 320, 1279, 320)

In [7]:
# Lets check the number of observations in each category

print("Count of 3 in Y_train", sum(Y_train['quality'] == 3))
print("Count of 4 in Y_train", sum(Y_train['quality'] == 4))
print("Count of 5 in Y_train", sum(Y_train['quality'] == 5))
print("Count of 6 in Y_train", sum(Y_train['quality'] == 6))
print("Count of 7 in Y_train", sum(Y_train['quality'] == 7))
print("Count of 8 in Y_train", sum(Y_train['quality'] == 8))

Count of 3 in Y_train 8
Count of 4 in Y_train 45
Count of 5 in Y_train 543
Count of 6 in Y_train 507
Count of 7 in Y_train 160
Count of 8 in Y_train 16

In [9]:
# Import the functionality of SMOTE

from imblearn.over_sampling import SMOTE

In [15]:
# We will balance the traing data
# 1. We will create SMOTE object

sm = SMOTE(random_state = 1234)

# 2. We will fit the SMOTE object on X_train, and Y_train --> fit.resample

X_train_new, Y_train_new = sm.fit_resample(X_train,Y_train)

In [19]:
print("Count of 3 in Y_train", sum(Y_train_new['quality'] == 3))
print("Count of 4 in Y_train", sum(Y_train_new['quality'] == 4))
print("Count of 5 in Y_train", sum(Y_train_new['quality'] == 5))
print("Count of 6 in Y_train", sum(Y_train_new['quality'] == 6))
print("Count of 7 in Y_train", sum(Y_train_new['quality'] == 7))
print("Count of 8 in Y_train", sum(Y_train_new['quality'] == 8))

Count of 3 in Y_train 543
Count of 4 in Y_train 543
Count of 5 in Y_train 543
Count of 6 in Y_train 543
Count of 7 in Y_train 543
Count of 8 in Y_train 543

In [21]:
# Step 4: Creating the model using the training data set

# step a: Create a model object 
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()

# step b: Fit the model object into training data to build a model
model = LR.fit(X_train_new, Y_train_new)
model

C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [22]:
# Step 5: Predict the values on test data using your model
Y_test['quality'] = model.predict(X_test)

In [23]:
Y_test

      quality
688         3
961         4
726         6
537         4
1544        8
...       ...
351         3
415         5
564         7
1124        4
147         5

[320 rows x 1 columns]

In [24]:
# Step 6: Creating the model using the training data set
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()

model = dtree.fit(X_train_new, Y_train_new)

model

DecisionTreeClassifier()

In [25]:
# STEP 7: Using this model Predict the X_test Case

Y_test['Pred_Quality'] = model.predict(X_test)

Y_test

      quality  Pred_Quality
688         3             5
961         4             6
726         6             6
537         4             5
1544        8             8
...       ...           ...
351         3             6
415         5             5
564         7             6
1124        4             5
147         5             5

[320 rows x 2 columns]

In [26]:
# STEP 6: To print the classification report

from sklearn.metrics import classification_report

print(classification_report(Y_test['quality'], Y_test['Pred_Quality']))

              precision    recall  f1-score   support

           3       1.00      0.07      0.12        30
           4       0.33      0.09      0.14        58
           5       0.43      0.64      0.51        87
           6       0.33      0.58      0.42        64
           7       0.34      0.47      0.40        38
           8       0.43      0.07      0.12        43

    accuracy                           0.38       320
   macro avg       0.48      0.32      0.29       320
weighted avg       0.43      0.38      0.32       320